[features]
seeds = false
[programs.localnet]
solana_twitter = "452VBruZdiZxs6mCZzLgx3R1ebUjCiXtCw67YACG6piM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/konradpodstawski/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
